[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rent_example = "6NUjZjUaC62bA6En3Cco9bhW4oKp7nqD6pBjmfcXKTyV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
